
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FundingEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FundingEvent
 * 
 */
export type FundingEventModel = runtime.Types.Result.DefaultSelection<Prisma.$FundingEventPayload>

export type AggregateFundingEvent = {
  _count: FundingEventCountAggregateOutputType | null
  _avg: FundingEventAvgAggregateOutputType | null
  _sum: FundingEventSumAggregateOutputType | null
  _min: FundingEventMinAggregateOutputType | null
  _max: FundingEventMaxAggregateOutputType | null
}

export type FundingEventAvgAggregateOutputType = {
  amount: number | null
}

export type FundingEventSumAggregateOutputType = {
  amount: number | null
}

export type FundingEventMinAggregateOutputType = {
  id: string | null
  strategyId: string | null
  amount: number | null
  timestamp: Date | null
}

export type FundingEventMaxAggregateOutputType = {
  id: string | null
  strategyId: string | null
  amount: number | null
  timestamp: Date | null
}

export type FundingEventCountAggregateOutputType = {
  id: number
  strategyId: number
  amount: number
  timestamp: number
  _all: number
}


export type FundingEventAvgAggregateInputType = {
  amount?: true
}

export type FundingEventSumAggregateInputType = {
  amount?: true
}

export type FundingEventMinAggregateInputType = {
  id?: true
  strategyId?: true
  amount?: true
  timestamp?: true
}

export type FundingEventMaxAggregateInputType = {
  id?: true
  strategyId?: true
  amount?: true
  timestamp?: true
}

export type FundingEventCountAggregateInputType = {
  id?: true
  strategyId?: true
  amount?: true
  timestamp?: true
  _all?: true
}

export type FundingEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FundingEvent to aggregate.
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundingEvents to fetch.
   */
  orderBy?: Prisma.FundingEventOrderByWithRelationInput | Prisma.FundingEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FundingEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundingEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundingEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FundingEvents
  **/
  _count?: true | FundingEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FundingEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FundingEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FundingEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FundingEventMaxAggregateInputType
}

export type GetFundingEventAggregateType<T extends FundingEventAggregateArgs> = {
      [P in keyof T & keyof AggregateFundingEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFundingEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateFundingEvent[P]>
}




export type FundingEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FundingEventWhereInput
  orderBy?: Prisma.FundingEventOrderByWithAggregationInput | Prisma.FundingEventOrderByWithAggregationInput[]
  by: Prisma.FundingEventScalarFieldEnum[] | Prisma.FundingEventScalarFieldEnum
  having?: Prisma.FundingEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FundingEventCountAggregateInputType | true
  _avg?: FundingEventAvgAggregateInputType
  _sum?: FundingEventSumAggregateInputType
  _min?: FundingEventMinAggregateInputType
  _max?: FundingEventMaxAggregateInputType
}

export type FundingEventGroupByOutputType = {
  id: string
  strategyId: string
  amount: number
  timestamp: Date
  _count: FundingEventCountAggregateOutputType | null
  _avg: FundingEventAvgAggregateOutputType | null
  _sum: FundingEventSumAggregateOutputType | null
  _min: FundingEventMinAggregateOutputType | null
  _max: FundingEventMaxAggregateOutputType | null
}

type GetFundingEventGroupByPayload<T extends FundingEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FundingEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FundingEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FundingEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FundingEventGroupByOutputType[P]>
      }
    >
  >



export type FundingEventWhereInput = {
  AND?: Prisma.FundingEventWhereInput | Prisma.FundingEventWhereInput[]
  OR?: Prisma.FundingEventWhereInput[]
  NOT?: Prisma.FundingEventWhereInput | Prisma.FundingEventWhereInput[]
  id?: Prisma.StringFilter<"FundingEvent"> | string
  strategyId?: Prisma.StringFilter<"FundingEvent"> | string
  amount?: Prisma.FloatFilter<"FundingEvent"> | number
  timestamp?: Prisma.DateTimeFilter<"FundingEvent"> | Date | string
}

export type FundingEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type FundingEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FundingEventWhereInput | Prisma.FundingEventWhereInput[]
  OR?: Prisma.FundingEventWhereInput[]
  NOT?: Prisma.FundingEventWhereInput | Prisma.FundingEventWhereInput[]
  strategyId?: Prisma.StringFilter<"FundingEvent"> | string
  amount?: Prisma.FloatFilter<"FundingEvent"> | number
  timestamp?: Prisma.DateTimeFilter<"FundingEvent"> | Date | string
}, "id">

export type FundingEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  _count?: Prisma.FundingEventCountOrderByAggregateInput
  _avg?: Prisma.FundingEventAvgOrderByAggregateInput
  _max?: Prisma.FundingEventMaxOrderByAggregateInput
  _min?: Prisma.FundingEventMinOrderByAggregateInput
  _sum?: Prisma.FundingEventSumOrderByAggregateInput
}

export type FundingEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.FundingEventScalarWhereWithAggregatesInput | Prisma.FundingEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.FundingEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FundingEventScalarWhereWithAggregatesInput | Prisma.FundingEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FundingEvent"> | string
  strategyId?: Prisma.StringWithAggregatesFilter<"FundingEvent"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"FundingEvent"> | number
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"FundingEvent"> | Date | string
}

export type FundingEventCreateInput = {
  id?: string
  strategyId: string
  amount: number
  timestamp?: Date | string
}

export type FundingEventUncheckedCreateInput = {
  id?: string
  strategyId: string
  amount: number
  timestamp?: Date | string
}

export type FundingEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundingEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundingEventCreateManyInput = {
  id?: string
  strategyId: string
  amount: number
  timestamp?: Date | string
}

export type FundingEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundingEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strategyId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FundingEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type FundingEventAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type FundingEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type FundingEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  strategyId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type FundingEventSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}



export type FundingEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  strategyId?: boolean
  amount?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["fundingEvent"]>

export type FundingEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  strategyId?: boolean
  amount?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["fundingEvent"]>

export type FundingEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  strategyId?: boolean
  amount?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["fundingEvent"]>

export type FundingEventSelectScalar = {
  id?: boolean
  strategyId?: boolean
  amount?: boolean
  timestamp?: boolean
}

export type FundingEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "strategyId" | "amount" | "timestamp", ExtArgs["result"]["fundingEvent"]>

export type $FundingEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FundingEvent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    strategyId: string
    amount: number
    timestamp: Date
  }, ExtArgs["result"]["fundingEvent"]>
  composites: {}
}

export type FundingEventGetPayload<S extends boolean | null | undefined | FundingEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FundingEventPayload, S>

export type FundingEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FundingEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FundingEventCountAggregateInputType | true
  }

export interface FundingEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FundingEvent'], meta: { name: 'FundingEvent' } }
  /**
   * Find zero or one FundingEvent that matches the filter.
   * @param {FundingEventFindUniqueArgs} args - Arguments to find a FundingEvent
   * @example
   * // Get one FundingEvent
   * const fundingEvent = await prisma.fundingEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FundingEventFindUniqueArgs>(args: Prisma.SelectSubset<T, FundingEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FundingEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FundingEventFindUniqueOrThrowArgs} args - Arguments to find a FundingEvent
   * @example
   * // Get one FundingEvent
   * const fundingEvent = await prisma.fundingEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FundingEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FundingEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FundingEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventFindFirstArgs} args - Arguments to find a FundingEvent
   * @example
   * // Get one FundingEvent
   * const fundingEvent = await prisma.fundingEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FundingEventFindFirstArgs>(args?: Prisma.SelectSubset<T, FundingEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FundingEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventFindFirstOrThrowArgs} args - Arguments to find a FundingEvent
   * @example
   * // Get one FundingEvent
   * const fundingEvent = await prisma.fundingEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FundingEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FundingEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FundingEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FundingEvents
   * const fundingEvents = await prisma.fundingEvent.findMany()
   * 
   * // Get first 10 FundingEvents
   * const fundingEvents = await prisma.fundingEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fundingEventWithIdOnly = await prisma.fundingEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FundingEventFindManyArgs>(args?: Prisma.SelectSubset<T, FundingEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FundingEvent.
   * @param {FundingEventCreateArgs} args - Arguments to create a FundingEvent.
   * @example
   * // Create one FundingEvent
   * const FundingEvent = await prisma.fundingEvent.create({
   *   data: {
   *     // ... data to create a FundingEvent
   *   }
   * })
   * 
   */
  create<T extends FundingEventCreateArgs>(args: Prisma.SelectSubset<T, FundingEventCreateArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FundingEvents.
   * @param {FundingEventCreateManyArgs} args - Arguments to create many FundingEvents.
   * @example
   * // Create many FundingEvents
   * const fundingEvent = await prisma.fundingEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FundingEventCreateManyArgs>(args?: Prisma.SelectSubset<T, FundingEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FundingEvents and returns the data saved in the database.
   * @param {FundingEventCreateManyAndReturnArgs} args - Arguments to create many FundingEvents.
   * @example
   * // Create many FundingEvents
   * const fundingEvent = await prisma.fundingEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FundingEvents and only return the `id`
   * const fundingEventWithIdOnly = await prisma.fundingEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FundingEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FundingEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FundingEvent.
   * @param {FundingEventDeleteArgs} args - Arguments to delete one FundingEvent.
   * @example
   * // Delete one FundingEvent
   * const FundingEvent = await prisma.fundingEvent.delete({
   *   where: {
   *     // ... filter to delete one FundingEvent
   *   }
   * })
   * 
   */
  delete<T extends FundingEventDeleteArgs>(args: Prisma.SelectSubset<T, FundingEventDeleteArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FundingEvent.
   * @param {FundingEventUpdateArgs} args - Arguments to update one FundingEvent.
   * @example
   * // Update one FundingEvent
   * const fundingEvent = await prisma.fundingEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FundingEventUpdateArgs>(args: Prisma.SelectSubset<T, FundingEventUpdateArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FundingEvents.
   * @param {FundingEventDeleteManyArgs} args - Arguments to filter FundingEvents to delete.
   * @example
   * // Delete a few FundingEvents
   * const { count } = await prisma.fundingEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FundingEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, FundingEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FundingEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FundingEvents
   * const fundingEvent = await prisma.fundingEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FundingEventUpdateManyArgs>(args: Prisma.SelectSubset<T, FundingEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FundingEvents and returns the data updated in the database.
   * @param {FundingEventUpdateManyAndReturnArgs} args - Arguments to update many FundingEvents.
   * @example
   * // Update many FundingEvents
   * const fundingEvent = await prisma.fundingEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FundingEvents and only return the `id`
   * const fundingEventWithIdOnly = await prisma.fundingEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FundingEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FundingEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FundingEvent.
   * @param {FundingEventUpsertArgs} args - Arguments to update or create a FundingEvent.
   * @example
   * // Update or create a FundingEvent
   * const fundingEvent = await prisma.fundingEvent.upsert({
   *   create: {
   *     // ... data to create a FundingEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FundingEvent we want to update
   *   }
   * })
   */
  upsert<T extends FundingEventUpsertArgs>(args: Prisma.SelectSubset<T, FundingEventUpsertArgs<ExtArgs>>): Prisma.Prisma__FundingEventClient<runtime.Types.Result.GetResult<Prisma.$FundingEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FundingEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventCountArgs} args - Arguments to filter FundingEvents to count.
   * @example
   * // Count the number of FundingEvents
   * const count = await prisma.fundingEvent.count({
   *   where: {
   *     // ... the filter for the FundingEvents we want to count
   *   }
   * })
  **/
  count<T extends FundingEventCountArgs>(
    args?: Prisma.Subset<T, FundingEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FundingEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FundingEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FundingEventAggregateArgs>(args: Prisma.Subset<T, FundingEventAggregateArgs>): Prisma.PrismaPromise<GetFundingEventAggregateType<T>>

  /**
   * Group by FundingEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FundingEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FundingEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FundingEventGroupByArgs['orderBy'] }
      : { orderBy?: FundingEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FundingEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFundingEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FundingEvent model
 */
readonly fields: FundingEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FundingEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FundingEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FundingEvent model
 */
export interface FundingEventFieldRefs {
  readonly id: Prisma.FieldRef<"FundingEvent", 'String'>
  readonly strategyId: Prisma.FieldRef<"FundingEvent", 'String'>
  readonly amount: Prisma.FieldRef<"FundingEvent", 'Float'>
  readonly timestamp: Prisma.FieldRef<"FundingEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FundingEvent findUnique
 */
export type FundingEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * Filter, which FundingEvent to fetch.
   */
  where: Prisma.FundingEventWhereUniqueInput
}

/**
 * FundingEvent findUniqueOrThrow
 */
export type FundingEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * Filter, which FundingEvent to fetch.
   */
  where: Prisma.FundingEventWhereUniqueInput
}

/**
 * FundingEvent findFirst
 */
export type FundingEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * Filter, which FundingEvent to fetch.
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundingEvents to fetch.
   */
  orderBy?: Prisma.FundingEventOrderByWithRelationInput | Prisma.FundingEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FundingEvents.
   */
  cursor?: Prisma.FundingEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundingEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundingEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FundingEvents.
   */
  distinct?: Prisma.FundingEventScalarFieldEnum | Prisma.FundingEventScalarFieldEnum[]
}

/**
 * FundingEvent findFirstOrThrow
 */
export type FundingEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * Filter, which FundingEvent to fetch.
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundingEvents to fetch.
   */
  orderBy?: Prisma.FundingEventOrderByWithRelationInput | Prisma.FundingEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FundingEvents.
   */
  cursor?: Prisma.FundingEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundingEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundingEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FundingEvents.
   */
  distinct?: Prisma.FundingEventScalarFieldEnum | Prisma.FundingEventScalarFieldEnum[]
}

/**
 * FundingEvent findMany
 */
export type FundingEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * Filter, which FundingEvents to fetch.
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FundingEvents to fetch.
   */
  orderBy?: Prisma.FundingEventOrderByWithRelationInput | Prisma.FundingEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FundingEvents.
   */
  cursor?: Prisma.FundingEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FundingEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FundingEvents.
   */
  skip?: number
  distinct?: Prisma.FundingEventScalarFieldEnum | Prisma.FundingEventScalarFieldEnum[]
}

/**
 * FundingEvent create
 */
export type FundingEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * The data needed to create a FundingEvent.
   */
  data: Prisma.XOR<Prisma.FundingEventCreateInput, Prisma.FundingEventUncheckedCreateInput>
}

/**
 * FundingEvent createMany
 */
export type FundingEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FundingEvents.
   */
  data: Prisma.FundingEventCreateManyInput | Prisma.FundingEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FundingEvent createManyAndReturn
 */
export type FundingEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * The data used to create many FundingEvents.
   */
  data: Prisma.FundingEventCreateManyInput | Prisma.FundingEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FundingEvent update
 */
export type FundingEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * The data needed to update a FundingEvent.
   */
  data: Prisma.XOR<Prisma.FundingEventUpdateInput, Prisma.FundingEventUncheckedUpdateInput>
  /**
   * Choose, which FundingEvent to update.
   */
  where: Prisma.FundingEventWhereUniqueInput
}

/**
 * FundingEvent updateMany
 */
export type FundingEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FundingEvents.
   */
  data: Prisma.XOR<Prisma.FundingEventUpdateManyMutationInput, Prisma.FundingEventUncheckedUpdateManyInput>
  /**
   * Filter which FundingEvents to update
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * Limit how many FundingEvents to update.
   */
  limit?: number
}

/**
 * FundingEvent updateManyAndReturn
 */
export type FundingEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * The data used to update FundingEvents.
   */
  data: Prisma.XOR<Prisma.FundingEventUpdateManyMutationInput, Prisma.FundingEventUncheckedUpdateManyInput>
  /**
   * Filter which FundingEvents to update
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * Limit how many FundingEvents to update.
   */
  limit?: number
}

/**
 * FundingEvent upsert
 */
export type FundingEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * The filter to search for the FundingEvent to update in case it exists.
   */
  where: Prisma.FundingEventWhereUniqueInput
  /**
   * In case the FundingEvent found by the `where` argument doesn't exist, create a new FundingEvent with this data.
   */
  create: Prisma.XOR<Prisma.FundingEventCreateInput, Prisma.FundingEventUncheckedCreateInput>
  /**
   * In case the FundingEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FundingEventUpdateInput, Prisma.FundingEventUncheckedUpdateInput>
}

/**
 * FundingEvent delete
 */
export type FundingEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
  /**
   * Filter which FundingEvent to delete.
   */
  where: Prisma.FundingEventWhereUniqueInput
}

/**
 * FundingEvent deleteMany
 */
export type FundingEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FundingEvents to delete
   */
  where?: Prisma.FundingEventWhereInput
  /**
   * Limit how many FundingEvents to delete.
   */
  limit?: number
}

/**
 * FundingEvent without action
 */
export type FundingEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FundingEvent
   */
  select?: Prisma.FundingEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FundingEvent
   */
  omit?: Prisma.FundingEventOmit<ExtArgs> | null
}
